---
# Commands to start on workspace startup
tasks:
  - name: "Prepare Environment"
    command: > 
      pip install --upgrade pip &&
      pip install --upgrade poetry &&
      poetry config virtualenvs.in-project true &&
      poetry install &&
      poetry shell &&
      beerlog

# Ports to expose on workspace startup
# ports:
#   - port: 8000
#     onOpen: open-preview
#     visibility: public

vscode:
  extensions:
    - "ms-python.python@2021.9.1218897484"
    - "tamasfe.even-better-toml"
    - "alexcvzz.vscode-sqlite"
    - "jdinhlife.gruvbox"
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.jupyter-keymap
